### ISSUE TITLE
Roman source file name uses Cyrillic Unicode characters

### ISSUE THREAD

**Issue by eliheuer** [lettersoup/Sofia-Sans#1]
`Sofia-Sans/sources/Sofia_Sans_ММ.glyphs` has `CYRILLIC CAPITAL LETTER EM U+041C` for the "MM" in the filename, but `Sofia-Sans/sources/Sofia_Sans_Italic_MM.glyphs` uses `LATIN CAPITAL LETTER M U+004D` for the "MM".

This can cause issues with build scripts, I suggest changing the filename to use `LATIN CAPITAL LETTER M U+004D` for all files.

**Comment by lettersoup** [comment]
All filenames are changed.
