### ISSUE TITLE
Copyright string in font name tables needs a Git URL for inclusion in the Google/fonts repository

### ISSUE THREAD

**Issue by eliheuer** [lettersoup/Sofia-Sans#15]
From the Google Fonts Spec:

### Font copyright

Copyright strings should be based on the following schema:

`Copyright { year } The { family } Project Authors ({ git_url })`

e.g

`Copyright 2019 The Oswald Project Authors (https://www.github.com/googlefonts/Oswald)`

If the project is OFL licensed, the first line of the OFL.txt file should be identical to the font copyright string.

**Comment by lettersoup** [comment]
@Eigi can fix that.
