### ISSUE TITLE
The variable font 'wght' (Weight) axis coordinate must be 700 on the 'Bold' instance.

### ISSUE THREAD

**Issue by eliheuer** [lettersoup/Sofia-Sans#16]
## Fontbakery report at commit: 1c01d6a

Fontbakery version: 0.7.16.dev7+g2ed6abcc

<summary><b>[1] SofiaSans[wdth,wght].ttf</b></summary>

<summary>🔥 <b>FAIL:</b> The variable font 'wght' (Weight) axis coordinate must be 700 on the 'Bold' instance.</summary>

* [com.google.fonts/check/varfont/bold_wght_coord](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/fvar.html#com.google.fonts/check/varfont/bold_wght_coord)
<pre>--- Rationale ---

The Open-Type spec&#x27;s registered design-variation tag &#x27;wght&#x27; available at
https://docs.microsoft.com/en-gb/typography/opentype/spec/dvaraxistag_wght does
not specify a required value for the &#x27;Bold&#x27; instance of a variable font.

But Dave Crossland suggested that we should enforce a required value of 700 in
this case.

</pre>

🔥 **FAIL** **The "wght" axis coordinate of the "Bold" instance must be 700. Got 573.6842 instead.**

**Comment by lettersoup** [comment]
This will be not possible. We have already static Bold CFF, wich are is in use and the VF Bold must match with it.
