### ISSUE TITLE
 No code pages defined in the OS/2 table ulCodePageRange1 and CodePageRange2 fields.

### ISSUE THREAD

**Issue by eliheuer** [lettersoup/Sofia-Sans#17]
## Fontbakery report at commit 1c01d6a

Fontbakery version: 0.7.16.dev7+g2ed6abcc

<summary><b>[1] SofiaSans[wdth,wght].ttf</b></summary>

<summary>🔥 <b>FAIL:</b> Check code page character ranges</summary>

* [com.google.fonts/check/code_pages](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/os2.html#com.google.fonts/check/code_pages)
<pre>--- Rationale ---

At least some programs (such as Word and Sublime Text) under Windows 7 do not
recognize fonts unless code page bits are properly set on the ulCodePageRange1
(and/or ulCodePageRange2) fields of the OS/2 table.

More specifically, the fonts are selectable in the font menu, but whichever
Windows API these applications use considers them unsuitable for any character
set, so anything set in these fonts is rendered with a fallback font of Arial.

This check currently does not identify which code pages should be set.
Auto-detecting coverage is not trivial since the OpenType specification leaves
the interpretation of whether a given code page is &quot;functional&quot; or not open to
the font developer to decide.

So here we simply detect as a FAIL when a given font has no code page declared
at all.

</pre>

* 🔥 **FAIL** No code pages defined in the OS/2 table ulCodePageRange1 and CodePageRange2 fields.

**Comment by lettersoup** [comment]
@Eigi can fix that one.
