### ISSUE TITLE
Check variable font instances have correct names

### ISSUE THREAD

**Issue by eliheuer** [lettersoup/Sofia-Sans#18]
## Fontbakery report at commit 1c01d6a

Fontbakery version: 0.7.18

<summary><b>[1] SofiaSans[wdth,wght].ttf</b></summary>
<summary>🔥 <b>FAIL:</b> Check variable font instances have correct names</summary>

* [com.google.fonts/check/varfont_instance_names](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/varfont_instance_names)

* 🔥 **FAIL** Instance name "HairLine" is incorrect. It should be "" [code: bad-name]
* 🔥 **FAIL** Instance name "UltraLight" is incorrect. It should be "Light" [code: bad-name]
* 🔥 **FAIL** Instance name "SemiLight" is incorrect. It should be "Light" [code: bad-name]
* 🔥 **FAIL** Instance name "Heavy" is incorrect. It should be "" [code: bad-name]
* 🔥 **FAIL** Instance name "Semi Cond HairLine" is incorrect. It should be "SemiCondensed" [code: bad-name]
* 🔥 **FAIL** Instance name "Semi Cond Thin" is incorrect. It should be "SemiCondensed Thin" [code: bad-name]
* 🔥 **FAIL** Instance name "Semi Cond UltraLight" is incorrect. It should be "SemiCondensed Light" [code: bad-name]
* 🔥 **FAIL** Instance name "Semi Cond ExtraLight" is incorrect. It should be "SemiCondensed ExtraLight" [code: bad-name]
* 🔥 **FAIL** Instance name "Semi Cond Light" is incorrect. It should be "SemiCondensed Light" [code: bad-name]
* 🔥 **FAIL** Instance name "Semi Cond SemiLight" is incorrect. It should be "SemiCondensed Light" [code: bad-name]
* 🔥 **FAIL** Instance name "Semi Cond Regular" is incorrect. It should be "SemiCondensed Regular" [code: bad-name]
* 🔥 **FAIL** Instance name "Semi Cond Medium" is incorrect. It should be "SemiCondensed Medium" [code: bad-name]
* 🔥 **FAIL** Instance name "Semi Cond SemiBold" is incorrect. It should be "SemiCondensed SemiBold" [code: bad-name]
* 🔥 **FAIL** Instance name "Semi Cond Bold" is incorrect. It should be "SemiCondensed Bold" [code: bad-name]
* 🔥 **FAIL** Instance name "Semi Cond ExtraBold" is incorrect. It should be "SemiCondensed ExtraBold" [code: bad-name]
* 🔥 **FAIL** Instance name "Semi Cond Black" is incorrect. It should be "SemiCondensed Black" [code: bad-name]
* 🔥 **FAIL** Instance name "Semi Cond Heavy" is incorrect. It should be "SemiCondensed" [code: bad-name]
* 🔥 **FAIL** Instance name "Cond HairLine" is incorrect. It should be "Condensed" [code: bad-name]
* 🔥 **FAIL** Instance name "Cond Thin" is incorrect. It should be "Condensed Thin" [code: bad-name]
* 🔥 **FAIL** Instance name "Cond UltraLight" is incorrect. It should be "Condensed Light" [code: bad-name]
* 🔥 **FAIL** Instance name "Cond ExtraLight" is incorrect. It should be "Condensed ExtraLight" [code: bad-name]
* 🔥 **FAIL** Instance name "Cond Light" is incorrect. It should be "Condensed Light" [code: bad-name]
* 🔥 **FAIL** Instance name "Cond SemiLight" is incorrect. It should be "Condensed Light" [code: bad-name]
* 🔥 **FAIL** Instance name "Cond Regular" is incorrect. It should be "Condensed Regular" [code: bad-name]
* 🔥 **FAIL** Instance name "Cond Medium" is incorrect. It should be "Condensed Medium" [code: bad-name]
* 🔥 **FAIL** Instance name "Cond SemiBold" is incorrect. It should be "Condensed SemiBold" [code: bad-name]
* 🔥 **FAIL** Instance name "Cond Bold" is incorrect. It should be "Condensed Bold" [code: bad-name]
* 🔥 **FAIL** Instance name "Cond ExtraBold" is incorrect. It should be "Condensed ExtraBold" [code: bad-name]
* 🔥 **FAIL** Instance name "Cond Black" is incorrect. It should be "Condensed Black" [code: bad-name]
* 🔥 **FAIL** Instance name "Cond Heavy" is incorrect. It should be "Condensed" [code: bad-name]
* 🔥 **FAIL** Instance name "Extra Cond HairLine" is incorrect. It should be "ExtraCondensed" [code: bad-name]
* 🔥 **FAIL** Instance name "Extra Cond Thin" is incorrect. It should be "ExtraCondensed Thin" [code: bad-name]
* 🔥 **FAIL** Instance name "Extra Cond UltraLight" is incorrect. It should be "ExtraCondensed Light" [code: bad-name]
* 🔥 **FAIL** Instance name "Extra Cond ExtraLight" is incorrect. It should be "ExtraCondensed ExtraLight" [code: bad-name]
* 🔥 **FAIL** Instance name "Extra Cond Light" is incorrect. It should be "ExtraCondensed Light" [code: bad-name]
* 🔥 **FAIL** Instance name "Extra Cond SemiLight" is incorrect. It should be "ExtraCondensed Light" [code: bad-name]
* 🔥 **FAIL** Instance name "Extra Cond Regular" is incorrect. It should be "ExtraCondensed Regular" [code: bad-name]
* 🔥 **FAIL** Instance name "Extra Cond Medium" is incorrect. It should be "ExtraCondensed Medium" [code: bad-name]
* 🔥 **FAIL** Instance name "Extra Cond SemiBold" is incorrect. It should be "ExtraCondensed SemiBold" [code: bad-name]
* 🔥 **FAIL** Instance name "Extra Cond Bold" is incorrect. It should be "ExtraCondensed Bold" [code: bad-name]
* 🔥 **FAIL** Instance name "Extra Cond ExtraBold" is incorrect. It should be "ExtraCondensed ExtraBold" [code: bad-name]
* 🔥 **FAIL** Instance name "Extra Cond Black" is incorrect. It should be "ExtraCondensed Black" [code: bad-name]
* 🔥 **FAIL** Instance name "Extra Cond Heavy" is incorrect. It should be "ExtraCondensed" [code: bad-name]

<hr>

* 🔥 **FAIL** This will cause problems with some of the Google Fonts systems that look up fonts by their style names. This must be fixed! [code: bad-instance-names]

**Comment by lettersoup** [comment]
Fontbakery does not give a non bad name for "HairLine" ,"Heavy". 
I don't think it is a good idea to name all three instances (Light, Ultra Light and Semi Light)  – Light:

>   "UltraLight" is incorrect. It should be "Light" 
> "SemiLight" is incorrect. It should be "Light" [code: bad-name]

I don't think it is a good idea to have different naming of the instances in the VF and the static fonts, wich are already in use.
