### ISSUE TITLE
Variable font weight coordinates are not multiples of 100

### ISSUE THREAD

**Issue by eliheuer** [lettersoup/Sofia-Sans#19]
## Fontbakery report at commit 1c01d6a

Fontbakery version: 0.7.18

<summary><b>[1] SofiaSans-Italic[wdth,wght].ttf</b></summary>

<summary>🔥 <b>FAIL:</b> Variable font weight coordinates must be multiples of 100.</summary>

* [com.google.fonts/check/varfont_weight_instances](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/varfont_weight_instances)
<pre>--- Rationale ---

The named instances on the weight axis of a variable font must have coordinates
that are multiples of 100 on the design space.

</pre>

* 🔥 **FAIL** Found a variable font instance with 'wght'=131.34328. This should instead be a multiple of 100. [code: bad-coordinate]
* 🔥 **FAIL** Found a variable font instance with 'wght'=180.59702. This should instead be a multiple of 100. [code: bad-coordinate]
* 🔥 **FAIL** Found a variable font instance with 'wght'=225.37312. This should instead be a multiple of 100. [code: bad-coordinate]
* 🔥 **FAIL** Found a variable font instance with 'wght'=265.67165. This should instead be a multiple of 100. [code: bad-coordinate]
* 🔥 **FAIL** Found a variable font instance with 'wght'=314.92537. This should instead be a multiple of 100. [code: bad-coordinate]
* 🔥 **FAIL** Found a variable font instance with 'wght'=447.87234. This should instead be a multiple of 100. [code: bad-coordinate]
* 🔥 **FAIL** Found a variable font instance with 'wght'=474.4681. This should instead be a multiple of 100. [code: bad-coordinate]
* 🔥 **FAIL** Found a variable font instance with 'wght'=570.21277. This should instead be a multiple of 100. [code: bad-coordinate]
* 🔥 **FAIL** Found a variable font instance with 'wght'=681.91489. This should instead be a multiple of 100. [code: bad-coordinate]
* 🔥 **FAIL** Found a variable font instance with 'wght'=793.61702. This should instead be a multiple of 100. [code: bad-coordinate]
* 🔥 **FAIL** Found a variable font instance with 'wght'=122.92577. This should instead be a multiple of 100. [code: bad-coordinate]
* 🔥 **FAIL** Found a variable font instance with 'wght'=168.77728. This should instead be a multiple of 100. [code: bad-coordinate]
* 🔥 **FAIL** Found a variable font instance with 'wght'=219.21397. This should instead be a multiple of 100. [code: bad-coordinate]
* 🔥 **FAIL** Found a variable font instance with 'wght'=242.13974. This should instead be a multiple of 100. [code: bad-coordinate]
* 🔥 **FAIL** Found a variable font instance with 'wght'=315.50218. This should instead be a multiple of 100. [code: bad-coordinate]
* 🔥 **FAIL** Found a variable font instance with 'wght'=379.69432. This should instead be a multiple of 100. [code: bad-coordinate]
* 🔥 **FAIL** Found a variable font instance with 'wght'=435.54869. This should instead be a multiple of 100. [code: bad-coordinate]
* 🔥 **FAIL** Found a variable font instance with 'wght'=473.41577. This should instead be a multiple of 100. [code: bad-coordinate]
* 🔥 **FAIL** Found a variable font instance with 'wght'=559.96909. This should instead be a multiple of 100. [code: bad-coordinate]
* 🔥 **FAIL** Found a variable font instance with 'wght'=673.57031. This should instead be a multiple of 100. [code: bad-coordinate]
* 🔥 **FAIL** Found a variable font instance with 'wght'=781.76198. This should instead be a multiple of 100. [code: bad-coordinate]
* 🔥 **FAIL** Found a variable font instance with 'wght'=889.95363. This should instead be a multiple of 100. [code: bad-coordinate]
* 🔥 **FAIL** Found a variable font instance with 'wght'=124.64789. This should instead be a multiple of 100. [code: bad-coordinate]
* 🔥 **FAIL** Found a variable font instance with 'wght'=159.15492. This should instead be a multiple of 100. [code: bad-coordinate]
* 🔥 **FAIL** Found a variable font instance with 'wght'=213.38028. This should instead be a multiple of 100. [code: bad-coordinate]
* 🔥 **FAIL** Found a variable font instance with 'wght'=238.02817. This should instead be a multiple of 100. [code: bad-coordinate]
* 🔥 **FAIL** Found a variable font instance with 'wght'=311.97183. This should instead be a multiple of 100. [code: bad-coordinate]
* 🔥 **FAIL** Found a variable font instance with 'wght'=361.26761. This should instead be a multiple of 100. [code: bad-coordinate]
* 🔥 **FAIL** Found a variable font instance with 'wght'=417.88618. This should instead be a multiple of 100. [code: bad-coordinate]
* 🔥 **FAIL** Found a variable font instance with 'wght'=480.4878. This should instead be a multiple of 100. [code: bad-coordinate]
* 🔥 **FAIL** Found a variable font instance with 'wght'=571.54472. This should instead be a multiple of 100. [code: bad-coordinate]
* 🔥 **FAIL** Found a variable font instance with 'wght'=668.29268. This should instead be a multiple of 100. [code: bad-coordinate]
* 🔥 **FAIL** Found a variable font instance with 'wght'=804.87805. This should instead be a multiple of 100. [code: bad-coordinate]
* 🔥 **FAIL** Found a variable font instance with 'wght'=126.3158. This should instead be a multiple of 100. [code: bad-coordinate]
* 🔥 **FAIL** Found a variable font instance with 'wght'=152.63158. This should instead be a multiple of 100. [code: bad-coordinate]
* 🔥 **FAIL** Found a variable font instance with 'wght'=194.73685. This should instead be a multiple of 100. [code: bad-coordinate]
* 🔥 **FAIL** Found a variable font instance with 'wght'=231.57895. This should instead be a multiple of 100. [code: bad-coordinate]
* 🔥 **FAIL** Found a variable font instance with 'wght'=310.52632. This should instead be a multiple of 100. [code: bad-coordinate]
* 🔥 **FAIL** Found a variable font instance with 'wght'=342.10526. This should instead be a multiple of 100. [code: bad-coordinate]
* 🔥 **FAIL** Found a variable font instance with 'wght'=489.2857. This should instead be a multiple of 100. [code: bad-coordinate]
* 🔥 **FAIL** Found a variable font instance with 'wght'=554.7619. This should instead be a multiple of 100. [code: bad-coordinate]
* 🔥 **FAIL** Found a variable font instance with 'wght'=661.90475. This should instead be a multiple of 100. [code: bad-coordinate]
* 🔥 **FAIL** Found a variable font instance with 'wght'=798.80952. This should instead be a multiple of 100. [code: bad-coordinate]

**Comment by lettersoup** [comment]
This will be not possible. We have already static CFF wich are in use and the VF instanses must match with them.

**Comment by davelab6** [comment]
The static cff files are considered legacy from the GF point of view, and we have library wide standards that can not be avoided. To keep compatibility with the legacy release, the GF release will have to have a different family name. Sofia Sans Pro, Sofia Sans Libre, etc

**Comment by lettersoup** [comment]
So from the foundry point of view I should have to explain to X number of users.
That their documents and websites are legacy and backwards compatibility is not a priority.

–
Botio Nikoltchev _ Malmöer Str. 14 _ 10439 Berlin _ Germany _ T 0049 176 38 210 436 _ www.lettersoup.de <http://www.lettersoup.de/>
–

**Comment by lettersoup** [comment]
I do not understand where is the issue with @vv-monsalve  proposal to  leave the min value of the Axis to 100 as Thin and discard the unsupported instances (HearLine, UltraLight, and SemiLight). And to change the current name "Heavy" to "Extrablack" and  map the weightClass to the GF supported 1000?

**Comment by vv-monsalve** [comment]
Inspecting [Hepta-Slab](https://fonts.google.com/specimen/Hepta+Slab?query=Hep) I can see now that we could recover the HairLine instance in the VF, mapping it to 1 weightClass value. The static fonts would continue being only the nine supported, Thin to Black, following the [GF Spec](https://github.com/googlefonts/gf-docs/tree/master/Spec#supported-styles).

This way, we would discard only the unsupported UltraLight and SemiLight.

@lettersoup  agreed to it as a good compromise to be able to publish the font under Sofia Sans.

This would be the instance scheme for Sofia Sans in GF:

```
Instance Name  | Weight name | weightClass | VF  | Static Instances 
---------------|-------------|-------------|-----|------------------
Hairline       | Thin        | 1           | •   | x
Thin           | Thin        | 100         | •   | •
ExtraLight     | ExtraLight  | 200         | •   | •
Light          | Light       | 300         | •   | •
Regular        | Regular     | 400         | •   | •
Medium         | Medium      | 500         | •   | •
SemiBold       | SemiBold    | 600         | •   | •
Bold           | Bold        | 700         | •   | •
ExtraBold      | ExtraBold   | 800         | •   | •    
Black          | Black       | 900         | •   | •
ExtraBlack     | ExtraBlack  | 1000        | •   | X
```

@davelab6 would you confirm this as a valid workaround?

**Comment by vv-monsalve** [comment]
Performing now FontBakery v7.31 test on the published Hepta-Slab VF, I see some reported Fails that probably we will receive also and therefore, we'll have to ignore.

<details>
<summary>🔥 <b>FAIL:</b> Variable font weight coordinates must be multiples of 100.</summary>

* [com.google.fonts/check/varfont_weight_instances](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/varfont_weight_instances)
<pre>--- Rationale ---

The named instances on the weight axis of a variable font must have coordinates
that are multiples of 100 on the design space.


</pre>

* 🔥 **FAIL** Found a variable font instance with 'wght'=1.0. This should instead be a multiple of 100. [code: bad-coordinate]

</details>
<details>
<summary>🔥 <b>FAIL:</b> Check variable font instances have correct coordinate values</summary>

* [com.google.fonts/check/varfont_instance_coordinates](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/varfont_instance_coordinates)

* 🔥 **FAIL** Instance "Hairline" wght value is "1.0". It should be "400.0" [code: bad-coordinate]
* 🔥 **FAIL** Further info can be found in our spec https://github.com/googlefonts/gf-docs/tree/master/Spec#axes

</details>
<details>
<summary>🔥 <b>FAIL:</b> Check variable font instances have correct names</summary>

* [com.google.fonts/check/varfont_instance_names](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/varfont_instance_names)

* 🔥 **FAIL** Following instances are not supported: 
	- Hairline

Further info can be found in our spec https://github.com/googlefonts/gf-docs/tree/master/Spec#fvar-instances [code: bad-instance-names]

</details>

**Comment by lettersoup** [comment]
From my side, it is a very nice solution and a good compromise between GF standards and backwards compatibility with the original CFF fonts. It allows us also to keep the name "Sofia Sans" and not to loose [the niece story behind this typeface.](https://www.lettersoup.de/sofia-sans/)

**Comment by davelab6** [comment]
> we would discard only the unsupported UltraLight and SemiLight.

They can be named in the stat table, i think. They just won't be named in the fvar table, or to non vf systems

**Comment by davelab6** [comment]
In the fontbakery check results above, why are the weights given with decimal point values? 

@lettersoup what are the values and names in the legacy CFF fonts, in widespread use?

**Comment by lettersoup** [comment]
@davelab6 In the repo there are three types of source files:
1. Source Original: includes the original MM files with non orthogonal design-space, weight values are the stem thickness of the master/instance and intstance names are the same in the legacy CFF. 

2. Source Variable Additional Master: to get a orthogonal design-space the Heavy Condensed master is duplicated (DSFix), weight values are the stem thickness of the master/instance and intstance names are the same in the legacy CFF

3. Source Variable Orthogonal Designspace: with orthogonal design-space, masters are remapped 100 to 900, thats why all the instances are recalculated and have weights given with decimal point values (to match with the original instances/CFFs)

**Comment by davelab6** [comment]
(1) used stems as os/2 values?

**Comment by lettersoup** [comment]
@davelab6 
No. As far as I understand you are asking about - why the interpolation weight values are with decimal points. The  OS/2 usWeightClass values are 100 to 900:


<img width="825" alt="Bildschirmfoto 2020-11-07 um 10 47 42" src="https://user-images.githubusercontent.com/6229652/98437940-b66b8a00-20e6-11eb-8736-795b6eb0c9b9.png">

**Comment by vv-monsalve** [comment]
> They can be named in the stat table, i think. They just won't be named in the fvar table, or to non vf systems

Working on this, I think it would be possible. Nevertheless, we'll need to accept the future Fontbakery fail complaining about the `Ultralight` not valid instance name in GF with 200 value, as we'll need to leave the GF valid instance name `Extra Light`  in the Stat table with the current 250 value.

**Comment by vv-monsalve** [comment]
> @lettersoup what are the values and names in the legacy CFF fonts, in widespread use?

@lettersoup Please send me via email the current CFF in widespread use. I'll need them as a reference for some proofs.

**Comment by vv-monsalve** [comment]
> (1) used stems as os/2 values?

@davelab6   (1) Used stems values. The workaround done with the [additional Master by Eli](https://github.com/lettersoup/Sofia-Sans/issues/6#issuecomment-524308398) was needed for the Variable font, as the original heavier masters differ in the stem value

![Screen Shot 2020-11-11 at 12 10 53](https://user-images.githubusercontent.com/48698976/98842133-1891fb00-2417-11eb-8140-14745807b343.png)
![Screen Shot 2020-11-11 at 12 11 00](https://user-images.githubusercontent.com/48698976/98842142-1b8ceb80-2417-11eb-9118-dfca4876643b.png)

**Comment by lettersoup** [comment]
> @lettersoup Please send me via email the current CFF in widespread use. I'll need them as a reference for some proofs.
@vv-monsalve the CFF are in the repo:
https://github.com/lettersoup/Sofia-Sans/tree/master/fonts/otf

**Comment by vv-monsalve** [comment]
> https://github.com/lettersoup/Sofia-Sans/tree/master/fonts/otf

Are those CFF still the original ones? If so, ok, I'll take them as reference.

**Comment by davelab6** [comment]
250 should only be used in cff fonts. ExtraLight should always be 200 in os2 TTFs and wght axis

**Comment by lettersoup** [comment]
> Are those CFF still the original ones? If so, ok, I'll take them as reference.

Yes, this are original CFFs.

**Comment by vv-monsalve** [comment]
> 250 should only be used in cff fonts. ExtraLight should always be 200 in os2 TTFs and wght axis

Oh yes, right. In that case, the inclusion of `Ultralight` in the Stat table wouldn't work in any case, so the instance will be discarded.
I'll continue working with [this approach](https://github.com/lettersoup/Sofia-Sans/issues/19#issuecomment-722698388).
