### ISSUE TITLE
Check `Google Fonts Latin Core` glyph coverage

### ISSUE THREAD

**Issue by eliheuer** [lettersoup/Sofia-Sans#20]
## Fontbakery report at commit 1c01d6a

Fontbakery version: 0.7.18

<summary><b>[1] SofiaSans-Italic[wdth,wght].ttf</b></summary>
<summary>🔥 <b>FAIL:</b> Check `Google Fonts Latin Core` glyph coverage.</summary>

* [com.google.fonts/check/glyph_coverage](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/glyph_coverage)
<pre>--- Rationale ---

Google Fonts expects that fonts in its collection support at least the minimal
set of characters defined in the `GF-latin-core` glyph-set.

</pre>

* 🔥 **FAIL** Missing required codepoints: 0x2215 (DIVISION SLASH) [code: missing-codepoints]

**Comment by lettersoup** [comment]
We agreed we Dave that Sofia Sans will be released with the codepage as it is.
