### ISSUE TITLE
The name is too similar to the Sofia Pro family

### ISSUE THREAD

**Issue by fitojb** [lettersoup/Sofia-Sans#21]
... and the designs are unrelated.

**Comment by cssobral2013** [comment]
@lettersoup - I propose the following name: Danube Sans.

**Comment by BulgarianHealer** [comment]
@fitojb and @cssobral2013 This is the official font of Sofia(Bulgaria capital).  There is no way to be renamed.

**Comment by lettersoup** [comment]
I´m aware of the issue about the naming-similarity with: Reina Sofia (designer: Edgar Belguinha Rodrigues, published in 2010), Sofia (designer: Latinotype, published 2011), Sofia Pro (designer: Mostardesign, published 2012) and Princess Sofia (designer: Tart Workshop published in 2012).
The Sofia Sans project started as a custom typeface for Sofia Municipality and the capital city of Bulgaria. You can reed the full story [here...](https://www.lettersoup.de/sofia-sans/)
It has the name-additive "Sans" so it is clearly not Pro, not Princess and not just Sofia.

@fitojb Yes we are not related to Mostardesign. As they are not related to Edgar Belguinha Rodrigues, Latinotype and Tart Workshop.

@cssobral2013 Danube is several hundert kilometers away from Sofia city...

**Comment by cssobral2013** [comment]
@lettersoup - Given this issue gone outta it's scope, can you close it? Thanks!
