### ISSUE TITLE
ExtraCondensed name

### ISSUE THREAD

**Issue by vv-monsalve** [lettersoup/Sofia-Sans#26]
As part of the job done in Sofia Sans for [publishing](https://github.com/lettersoup/Sofia-Sans/pulls) in Google Fonts, the width values were mapped to the ones required per the GF Spec about the [Axes](https://github.com/googlefonts/gf-docs/tree/master/Spec#axis-particles) and its coordinated values.

Although according to the width values on the Spec the name for the narrower font should be "Ultra Condensed", so far I've kept the current Extra Condensed name, due to backwards compatibility goals with the original CFF fonts. 

However, this is something that would need @m4rc1e and @davelab6 confirmation on whether if it would be possible or not to keep the original name.
<br>

```
Font Names                 | design Width value | GF Spec | GF expected name 
---------------------------|--------------------|---------|-----------------
Sofia Snas                 | 100                | 100     | - (elided)
Sofia Sans Semi Condensed  | 89                 | 87.5    | SemiCondensed
Sofia Sans Condensed       | 57                 | 75      | Condensed
Sofia Sans Extra Condensed | 30                 | 50      | UltraCondensed
```

**Comment by m4rc1e** [comment]
Please drop the original names and width values in favour of the GF Spec values please.

**Comment by vv-monsalve** [comment]
@lettersoup, I've done a new [PR](https://github.com/lettersoup/Sofia-Sans/pull/27) that includes the change to Ultra Condensed

**Comment by vv-monsalve** [comment]
Done, closing this here.
