### ISSUE TITLE
New Fail reported for the VF

### ISSUE THREAD

**Issue by vv-monsalve** [lettersoup/Sofia-Sans#28]
New FB tests were performed using the last version 0.7.33 which includes new checks to outlines and the following Fail was reported:

<details>
<summary>🔥 <b>FAIL:</b> Check glyphs do not have components which are themselves components.</summary>

* [com.google.fonts/check/glyf_nested_components](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/glyf.html#com.google.fonts/check/glyf_nested_components)
<pre>--- Rationale ---
ve been bugs rendering variable fonts with nested components. Additionally,
some static fonts with nested components have been reported to have rendering
and printing issues. (See googlefonts/fontbakery#2961 and
arrowtype/recursive#412.)

</pre>

* 🔥 **FAIL** The following glyphs have components which themselves are component glyphs:
	* omicrontonos.sc [code: found-nested-components]

</details>

**Comment by lettersoup** [comment]
Ok, omicorontonos.sc is no longer nested component.
