### ISSUE TITLE
Warns in static fonts

### ISSUE THREAD

**Issue by vv-monsalve** [lettersoup/Sofia-Sans#29]
New FB tests were performed using the last version 0.7.33 which includes new checks to outlines and new Warns were reported. The following are taken as an example of the ones reported for each font in the family.

<details>
<summary>⚠ <b>WARN:</b> Do any segments have colinear vectors?</summary>

* [com.google.fonts/check/outline_colinear_vectors](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/<Section: Outline Correctness Checks>.html#com.google.fonts/check/outline_colinear_vectors)
<pre>--- Rationale ---

This test looks for consecutive line segments which have the same angle. This
normally happens if an outline point has been added by accident.

This test is not run for variable fonts, as they may legitimately have colinear
vectors.

</pre>

* ⚠ **WARN** The following glyphs have colinear vectors:
	* fraction: L<<-106.0,-24.0>--<40.0,344.0>> -> L<<40.0,344.0>--<173.0,684.0>>
	* fraction: L<<300.0,679.0>--<153.0,320.0>> -> L<<153.0,320.0>--<21.0,-29.0>>
	* onehalf: L<<299.0,-24.0>--<445.0,344.0>> -> L<<445.0,344.0>--<578.0,684.0>>
	* onehalf: L<<706.0,679.0>--<559.0,320.0>> -> L<<559.0,320.0>--<426.0,-29.0>>
	* onequarter: L<<299.0,-24.0>--<445.0,344.0>> -> L<<445.0,344.0>--<578.0,684.0>>
	* onequarter: L<<706.0,679.0>--<559.0,320.0>> -> L<<559.0,320.0>--<426.0,-29.0>>
	* percent: L<<172.0,16.0>--<328.0,349.0>> -> L<<328.0,349.0>--<456.0,647.0>>
	* percent: L<<581.0,640.0>--<433.0,327.0>> -> L<<433.0,327.0>--<296.0,9.0>>
	* perthousand: L<<172.0,16.0>--<328.0,349.0>> -> L<<328.0,349.0>--<456.0,647.0>>
	* perthousand: L<<581.0,640.0>--<433.0,327.0>> -> L<<433.0,327.0>--<296.0,9.0>> and 7 more. [code: found-colinear-vectors]

</details>
<details>
<summary>⚠ <b>WARN:</b> Do outlines contain any semi-vertical or semi-horizontal lines?</summary>

* [com.google.fonts/check/outline_semi_vertical](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/<Section: Outline Correctness Checks>.html#com.google.fonts/check/outline_semi_vertical)
<pre>--- Rationale ---

This test detects line segments which are nearly, but not quite, exactly
horizontal or vertical. Sometimes such lines are created by design, but often
they are indicative of a design error.

This test is disabled for italic styles, which often contain nearly-upright
lines.

</pre>

* ⚠ **WARN** The following glyphs have semi-vertical/semi-horizontal lines:
	* m.sc: L<<172.0,186.0>--<171.0,12.0>>
	* m.sc: L<<413.0,11.0>--<412.0,187.0>>
	* omega: L<<453.0,166.0>--<452.0,360.0>>
	* omega: L<<595.0,359.0>--<596.0,157.0>>
	* omegatonos: L<<453.0,166.0>--<452.0,360.0>>
	* omegatonos: L<<595.0,359.0>--<596.0,157.0>>
	* one.dnom: L<<139.0,101.0>--<140.0,305.0>>
	* one.numr: L<<139.0,332.0>--<140.0,536.0>>
	* onehalf: L<<139.0,332.0>--<140.0,536.0>>
	* onequarter: L<<139.0,332.0>--<140.0,536.0>> and 12 more. [code: found-semi-vertical]

</details>

Please inspect the complete reports for static fonts and ensure everything is ok.

- [Sofia Sans](https://github.com/vv-monsalve/Sofia-Sans/blob/QA-Sofia/fonts/ttf/static/qaSofia-static-09.md)
- Sofia Sans [SemiCondensed](https://github.com/vv-monsalve/Sofia-Sans/blob/QA-Sofia/fonts/ttf/static/qaSofiaSemiCond-05.md)
- Sofia Sans [Condensed](https://github.com/vv-monsalve/Sofia-Sans/blob/QA-Sofia/fonts/ttf/static/qaSofiaCond-04.md)
- Sofia sans[ UltraCondensed](https://github.com/vv-monsalve/Sofia-Sans/blob/QA-Sofia/fonts/ttf/static/qaSofiaUltraCond-01.md)

**Comment by lettersoup** [comment]
Checked all the warnings, they are ok.

**Comment by vv-monsalve** [comment]
Please bear in mind that the actual font files (not the source files) should be inspected to rule out any risky situation. Some of the reported warn about situations like this:

* ⚠ **WARN** The following glyphs have jaggy segments:
	* uni0446: B<<426.0,67.0>-<423.0,44.0>-<421.0,21.0>>/L<<421.0,21.0>--<421.0,22.0>> = 4.969740728110289 [code: found-jaggy-segments]


![Screen Shot 2020-12-07 at 12 38 29](https://user-images.githubusercontent.com/48698976/101385865-5b19ec80-388a-11eb-95a1-440ceb46cb76.png)

zoom in: the produced font has a really short and collinear segment with a wrong smooth connection.

![Screen Shot 2020-12-07 at 12 39 41](https://user-images.githubusercontent.com/48698976/101385884-61a86400-388a-11eb-8542-e3bef777e98b.png)

In this case, this could be avoided by suppressing the overlapping straight shapes, using corners instead

![Screen Shot 2020-12-07 at 12 51 02](https://user-images.githubusercontent.com/48698976/101386955-d203b500-388b-11eb-9fa0-0b5e80278012.png)

**Comment by lettersoup** [comment]
Sorry I´f might missed that. It is fixed now.
