### ISSUE TITLE
non-rectangular designspace

### ISSUE THREAD

**Issue by eliheuer** [lettersoup/Sofia-Sans#6]
The source files have a non-rectangular designspace, this causes a fontmake build error.

**Comment by eliheuer** [comment]
I have been trying to fix this using this script: https://github.com/thundernixon/Encode-Sans/blob/master/sources/scripts/helpers/fix-designspace.py

**Comment by eliheuer** [comment]
More info on this issue from Encode Sans here: https://github.com/thundernixon/Encode-Sans/tree/master/docs/01-morphing-non-rect-designspace

**Comment by lettersoup** [comment]
To fix that I have to duplicate both Regular and both Bold masters. This will make the source file unnecessarily complicate (it will be useful just for the VF production). 
The math fix does not work because the instances do not match with the original ones (I´f already tried that).
I suggest to send you a source file with duplicated masters just for the VF production and to keep the simple ones on Github. Please let us discuss it with @davelab6
<img width="178" alt="Bildschirmfoto 2019-08-20 um 18 20 19" src="https://user-images.githubusercontent.com/6229652/63369412-27a70c00-c380-11e9-86fa-b731100d0a71.png">

**Comment by eliheuer** [comment]
You could add this to the repository, but it doesn't seem like a great solution. There has to be a better way to do this, if there isn't the upstream build tools need to be updated.

The fonts need to be able to be built using the public git repo and instructions in the README/docs.

**Comment by eliheuer** [comment]
@lettersoup could you help me compose an issue to post on the fontmake issue tracker about this here? I'm not sure exactly why the designspace is set up the way it is.

Ideally a Glyphs source file shouldn't need any hacks like this to work with with fontmake.

**Comment by lettersoup** [comment]
Yes you are right it is not a great solution at all, its actually a hack. So if the VF is not a priority I like to keep the source files as they are! 

> I'm not sure exactly why the designspace is set up the way it is.

I´m not sure if I understand the question. 
At the beginning of the Sofia Sans project it wasn't planed to produce a VF. The masters are set as usual for such projects (Ultra Condensed -Regula - Extended) in Glyphs App, wich allows non-rectangular designspace interpolation.  Please see ["Setting master values"](https://glyphsapp.com/tutorials/multiple-masters-part-1-setting-up-masters):
The weight value of the masters are set as the measurements of lowercase stems of the instances. I know this method is different than the one [Adobe advised with 0:1000](https://www-cdf.fnal.gov/offline/PostScript/5091.Design_MM_Fonts.pdf) values. But in the prevariable times it seemed as a good idea and was way easier for to work width.

> Ideally a Glyphs source file shouldn't need any hacks like this to work with with fontmake.

I agree on that. Hopefully Georg will change it in Glyph 3. At the moment there is a custom parameter Axis Location, but unfortunately it does not work proper:
https://glyphsapp.com/tutorials/creating-a-variable-font

**Comment by eliheuer** [comment]
What do you think @m4rc1e? I don't see duplicating masters as a solution and would much rather fix this with a script like Encode Sans did.

**Comment by eliheuer** [comment]
I think @bghryct and I figured out a somewhat better way to do this by adding only one extrapolated master at 180 weight and 30 width.

**Comment by eliheuer** [comment]
I talked to Dave about this today and he said we need to fix this in the `avar` table, adding helper masters wont work. 

I think everything we need to do this can be found in this repo: https://github.com/mjlagattuta/Hepta-Slab

**Comment by lettersoup** [comment]
@eliheuer, I´m not sure what you mean. Could you explain a little bit more precise please.

**Comment by eliheuer** [comment]
Here is a drawing of the solution we came up with yesterday for fixing this with only one master:

![sofia-ds](https://user-images.githubusercontent.com/5162664/63594612-e6337e00-c584-11e9-9f8c-2974a3eb949e.jpg)

I will PR this file, since it builds with fontmake, but Hepta Slab had a similar issue and was able to fix it without using any hacks such as adding masters.

**Comment by lettersoup** [comment]
As far I can see Hepta Slab uses the Axes Location Custom Parameter. I tried that solution but it did not work.

**Comment by eliheuer** [comment]
I made a pull request that has the above single master designspace solution and a working Fontmake build script: https://github.com/lettersoup/Sofia-Sans/pull/11

I think Hepta Slab used a script to update the `avar` table, like [this one](https://github.com/thundernixon/Encode-Sans/blob/master/sources/scripts/helpers/fix-designspace.py). More backround on this is [here](https://forum.glyphsapp.com/t/generating-an-avar-table/9337). As far as I know, there was no Glyphs custom parameter for this at that time. 

However, there might be some good news. Looking at the changelog for Glyphs 2.6.2 (1261), I see that there was a new custom parameter added yeasterday that might fix this in the source file without any post-build steps:

- Add "Axis Mappings" custom parameter to support avar table

I'll play around with this and see if It might be a solution.

**Comment by lettersoup** [comment]
This a great news!! Many thanks Eli!

**Comment by davelab6** [comment]
> So if the VF is not a priority I like to keep the source files as they are

I wonder if it makes sense to accept default on the VF front, and for @lettersoup and @vv-monsalve to work on a set of static font families to release in GF that way, and then we could look to make a 'Sofia Sans Flex' in the future that has for example an extensive optical size axis, and release that as a separate family that is obviously incompatible.

**Comment by vv-monsalve** [comment]
I thought about a statics-only release yesterday when reading again the issues as it would retain the backwards compatibility on Sofia Sans while making it available to a broader audience, but the VF part was my concern. So the idea of publishing it later as a non-compatible but related and bigger variable font project sounds like a good alternative.

**Comment by m4rc1e** [comment]
Since the family isn't released, can't we just redistribute the weight axis so we end up with an orthogonal designspace instead? I don't think Eli's solution of simply adding a master is sufficient,.

**Comment by lettersoup** [comment]
@m4rc1e I think we did it a year ago:
https://github.com/lettersoup/Sofia-Sans/tree/master/sources/Legacy-sources/SourceVariableOrtogonalDesignspace

**Comment by lettersoup** [comment]
@davelab6 @vv-monsalve I wonder if it make sense first release the static fonts and than wait for the avar two table, wich will allow us the variations in two axes and then publish a VF.
Daves solution with 'Sofia Sans Flex' seems also very nice, but it will increase the file size because of the optical axis.
